name: Template

on:
  workflow_call:
    inputs:
    #   clientid:
    #     required: true
    #     type: string
    #   username:
    #     required: true
    #     type: string
    #   tenantid:
    #     required: true
    #     type: string
    secrets:
      clientsecret:
        required: true
      clientid:
        required: true
      username:
        required: true
      password:
        required: true
      tenantid:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Running pre-build tests
        run: |
          $directory = (Get-Item .).FullName
          . "./Pipeline Scripts/Invoke-PreBuildTests.ps1" -Folder $directory
        shell: pwsh
      
      - name: Running variable tests
        env:
          CLIENTID: ${{ secrets.clientid }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          CLIENTSECRET: ${{ secrets.clientsecret }}
          TENANTID: ${{ secrets.TENANTID }}
        run: |
          . "./Pipeline Scripts/Test-Variables.ps1"
        shell: pwsh
