name: Template

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      CLIENTSECRET:
        required: true
      CLIENTID:
        required: true
      USERNAME:
        required: false
      TENANTID:
        required: false
      PASSWORD:
        required: false

jobs:
  reusable_workflow_job:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Running pre-build tests
        run: |
          $directory = (Get-Item .).FullName
          . "./Pipeline Scripts/Invoke-PreBuildTests.ps1" -Folder $directory
        shell: pwsh
      
      - name: Running variable tests
        env:
          CLIENTID: ${{ secrets.CLIENTID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
          TENANTID: ${{ secrets.TENANTID }}
        run: |
          . "./Pipeline Scripts/Test-Variables.ps1"
        shell: pwsh
