name: "m365x912454.onmicrosoft.com - Intune"

jobs:
  deploy:
    environment: m365x912454.onmicrosoft.com
    uses: "mariussm/action-testing-2/.github/workflows/1 - template.yml@main"
    secrets:
      #password: "${{secrets.password}}"
      clientsecret: "${{secrets.clientsecret}}"
      clientid: "${{secrets.clientid}}"
      #username: "${{secrets.username}}"
      #tenantid: "${{secrets.tenantid}}"

on:
  push:
    branches: [ main ]
  workflow_dispatch: