name: "m365x912454.onmicrosoft.com - Intune"

jobs:
  deploy:
    environment: m365x912454.onmicrosoft.com
    uses: "mariussm/action-testing-2/.github/workflows/1 - template.yml@main"
    with:
      clientid: ${{secrets.clientid}}
      username: ${{secrets.username}}
      username: ${{secrets.tenantid}}
    secrets:
      password: ${{secrets.password}}
      clientsecret: ${{secrets.clientsecret}}

on:
  push:
    branches: [ main ]
  workflow_dispatch: