name: "m365x912454.onmicrosoft.com - Intune"

jobs:
  call-template:
    uses: "mariussm/action-testing-2/.github/workflows/1 - template.yml@main"
    with:
      environment: m365x912454.onmicrosoft.com
      clientid: ${{secrets.clientid}}
    secrets:
      clientsecret: ${{secrets.clientsecret}}

on:
  push:
    branches: [ main ]
  workflow_dispatch: