name: "m365x912454.onmicrosoft.com - Intune"

env:
  tenantdomain: m365x912454.onmicrosoft.com

jobs:
  deploy:
    # environment: m365x912454.onmicrosoft.com
    uses: "mariussm/action-testing-2/.github/workflows/1 - template.yml@main"
    with:
      ENVIRONMENT: ${{ env.tenantdomain }}
    secrets:
      CLIENTSECRET: "${{ secrets.CLIENTSECRET }}"
      CLIENTID: "${{ secrets.CLIENTID }}"
      USERNAME: "${{ secrets.USERNAME }}"
      TENANTID: "${{ secrets.TENANTID }}"
      PASSWORD: "${{ secrets.PASSWORD }}"
on:
  push:
    branches: [ main ]
  workflow_dispatch: