name: "m365x912454.onmicrosoft.com - Intune"

jobs:
  deploy:
    # environment: m365x912454.onmicrosoft.com
    uses: "mariussm/action-testing-2/.github/workflows/1 - template.yml@main"
    with:
      ENVIRONMENT: m365x912454.onmicrosoft.com
    secrets:
      clientsecret: "${{secrets.clientsecret}}"
      clientid: "${{secrets.clientid}}"
      USERNAME: "${{secrets.USERNAME}}"
      TENANTID: "${{secrets.TENANTID}}"
      PASSWORD: "${{secrets.PASSWORD}}"
on:
  push:
    branches: [ main ]
  workflow_dispatch: